name: Testing

on:
  push:
    branches:
      - [sample_estimates_devel]
  pull_request:
    branchess:
      - [sample_estimates_devel]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Test with pytest
        run: |
          mpirun -np 4 python3 -m pytest tests/random_problem/test_split_samples.py 
